### ISSUE TITLE
please add dependency to package.json

### ISSUE THREAD

**Issue by wbxl2000** [AIDungeon/GPT-3-Encoder#36]
<img width="468" alt="image" src="https://user-images.githubusercontent.com/57169560/229343945-8c361406-527b-4226-be97-f7b2f836c0d9.png">

**Comment by cccjaccck** [comment]
maybe this ? #32

**Comment by wbxl2000** [comment]
repeat https://github.com/latitudegames/GPT-3-Encoder/issues/32
